defaults:
  - _self_
  # - data_sampling: img
  - data_sampling: pix
  - prepro: dataset
  # - prepro: pixwise
  - model: MLP_BatchNorm
  # - model: CNN1d_BatchNorm
  # - model: CNN1d_LayerNorm
  # - model: MLP_InstanceNorm
  # - model: MCE_ST
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  run:
    dir: './runs/${now:%Y-%m-%d}/${now:%H-%M}/hydra_log'
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: unchi
    storage: null
    n_trials: 25
    n_jobs: 2

mlflow: 
  runname: unchi

train_parameter:
  lr: 0.001
  scheduler_step: 10
  scheduler_gamma: 0.01
  epochs: 300
  batch_size: 128

dataload:
  pix: all
  # pix: white
  # pix: black
  class_num: 16

split:
  date_split: False
  # date_split: True
  train_rate: 0.8
  seed: 0

noise:
  flag: True
  # flag: False
  pix_num: 10

data_aug:
  # flag: True
  flag: False
  thresh: 150
  max_pix_num: 1

sampling:
  # flag: True
  flag: False

pca:
  pca_flag: False
  n_component: 5