batch_size: 128
train_parameter:
  epochs: 300
  lr: 0.001
  scheduler_gamma: 0.6

# model
input_dim: 151
output_dim: 16
dropout_prob: 0.5

# device
device: 'cuda:0'


train:
  feature: '/mnt/hdd1/youta/ws/HSI_penguinID/dataset/MLP_pretrain/train_data.csv'
  target: '/mnt/hdd1/youta/ws/HSI_penguinID/dataset/MLP_pretrain/train_target.csv'
validation:
  feature: '/mnt/hdd1/youta/ws/HSI_penguinID/dataset/MLP_pretrain/validation_data.csv'
  target: '/mnt/hdd1/youta/ws/HSI_penguinID/dataset/MLP_pretrain/validation_target.csv'
test:
  feature: '/mnt/hdd1/youta/ws/HSI_penguinID/dataset/MLP_pretrain/test_data.csv'
  target: '/mnt/hdd1/youta/ws/HSI_penguinID/dataset/MLP_pretrain/test_target.csv'